#include <stdlib.h>
#include <pthread.h>
#include <semaphore.h>   
#include <stdio.h>   
#include <unistd.h>   
#include <errno.h>
#include <sys/types.h>   
#include <sys/stat.h>   
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <sys/time.h>
#include <sys/timeb.h>
#include <sys/mman.h>
#include <linux/fcntl.h>
#include <sys/stat.h>
